/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logigear_automation_mobile_model_DeviceModel */

#ifndef _Included_com_logigear_automation_mobile_model_ScreenshotClientModel
#define _Included_com_logigear_automation_mobile_model_ScreenshotClientModel
#ifdef __cplusplus
extern "C" {
#endif

#define SCREENSHOT_SERVICE	"com.apple.mobile.screenshotr"

/*
 * Class:     com_logigear_automation_mobile_model_DeviceModel
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_logigear_automation_mobile_model_ScreenshotClientModel_connect
  (JNIEnv * env, jobject thizz, jlong nDevice);

JNIEXPORT jbyteArray JNICALL Java_com_logigear_automation_mobile_model_ScreenshotClientModel_takeScreenshot
(JNIEnv * env, jobject thizz, jlong nClient);

#ifdef __cplusplus
}
#endif
#endif
