/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logigear_automation_mobile_model_DeviceModel */

#ifndef _Included_com_logigear_automation_mobile_model_DeviceModel
#define _Included_com_logigear_automation_mobile_model_DeviceModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logigear_automation_mobile_model_DeviceModel
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_logigear_automation_mobile_model_DeviceModel_initialize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
